[global]
node_id = 3001
host = "localhost"
cluster_name = 'cluster_xxx'
store_metrics = true

[deployment]
# mode = 'query_tskv'
# cpu = 8
# memory = 16

[meta]
service_addr = ["127.0.0.1:8901"]
report_time_interval = "30s"
usage_schema_cache_size = "32K" # 32KB
cluster_schema_cache_size = "32K" # 32KB

[query]
max_server_connections = 10240
query_sql_limit = "16777216B"  # 16 * 1024 * 1024
write_sql_limit = "167772160B" # 160 * 1024 * 1024
auth_enabled = false
read_timeout = "3000ms"
write_timeout = "3000ms"
stream_trigger_cpu = 1
stream_executor_cpu = 2
sql_record_timeout = "10s"

[storage]
# Directory for summary: $path/summary/
# Directory for index: $path/index/$database/
# Directory for tsm: $path/data/$database/tsm/
# Directory for delta: $path/data/$database/delta/
path = '/tmp/cnosdb/3001/db'
max_summary_size = "128M"            # 134217728
base_file_size = "16M"               # 16777216
flush_req_channel_cap = 16
max_cached_readers = 32
compact_trigger_file_num = 4
compact_trigger_cold_duration = "1h"
max_compact_size = "2G"              # 2147483648
max_concurrent_compaction = 4
collect_compaction_metrics = false
strict_write = false
reserve_space = "0"
max_datablock_size = "100KB"

[wal]
path = '/tmp/cnosdb/3001/wal'
max_file_size = "1G"                 # 1073741824
sync = false

[cache]
max_buffer_size = "512M" # 536,870,912
partition = 16           # default memcache partition number

[log]
level = 'info'
path = '/tmp/cnosdb/3001/log'
max_file_count = 10
file_rotation = "daily"

[security]
# [security.tls_config]
# certificate = "./config/tls/server.crt"
# private_key = "./config/tls/server.key"

[service]
http_listen_port = 8922
grpc_listen_port = 8923
grpc_enable_gzip = false
flight_rpc_listen_port = 8924
tcp_listen_port = 8925
vector_listen_port = 8926
jaeger_rpc_listen_port = 8927
enable_report = true


[cluster]
raft_logs_to_keep = 5000
snapshot_holding_time = "3600s"
lmdb_max_map_size = "1024000000B"
heartbeat_interval = "3000ms"
trigger_snapshot_interval = "600s"
install_snapshot_timeout = "3600000ms"
send_append_entries_timeout = "5000ms"

# [trace]
# auto_generate_span = true
# otlp_endpoint = 'http://localhost:4317'
